### PR TITLE
replace vfs_read with kernel_read to fix loading on some 4.14+

### PR DESCRIPTION
**Pull request by ianmatt**

### CODE REVIEW

**Comment by antonio-petricca** [comment]
Thank you @ianmatt for your contribution. 

Before merging I would ask you, if you agree, to provide me your real name and email and add you to the project credits.

After that I will check you patch against the older kernels on Debian like distributions too.

Regards,
Antonio

**Comment by antonio-petricca** [comment]
( Linked to issue #1 )

**Comment by antonio-petricca** [comment]
I have test it on Ubuntu/Mint (4.12 to 4.19) and it works.

Unfortunately on Arch 4.18.16 I get this error:

image

**Comment by ianmatt** [comment]
can you add manually in ifslinux/config_check.c the line
_#include <linux/version.h>_
before
 _#include <linux/kernel.h>
 #include <linux/slab.h>
 #include <linux/fs.h>_
don't have any arch distro at hand to test

**Comment by antonio-petricca** [comment]
I confirm that it works now, but I have to test kernels on debian too...

As I asked you earlier, do you want your name and email into the credits?

Thank you again.

**Comment by ianmatt** [comment]
no, credits are fine with you alone, let's not break that.
good job on putting all this together btw!

**Comment by ianmatt** [comment]
Maybe worth a separate note
I have been running this extensively, for months now, on the 4.15 kernel (since I use a common NTFS partition for my VMs disks that I must access on my dual-boot from Linux or Windows, depending of the scenario) and had zero issues that could indicate the module. However, on some rare occasions, I had the NTFS partition fail to mount (it's mounted automatically at boot with fstab) due to what I guess to be some race condition (the attempted mount was happening before the ufsd module was loaded), fixed this by adding it to the initramfs (on ubuntu distro one can add _ufsd_ in the _/etc/initramfs-tools/modules_ file and run _sudo update-initramfs -u_) this way ufsd module will always be loaded early in the boot step.

**Comment by antonio-petricca** [comment]
Hi, I have just released [the fix](https://github.com/antonio-petricca/paragon-ufsd-ntfs-driver-porting/tree/4.19-hotfix-01-archlinux).

> fixed this by adding it to the initramfs (on ubuntu distro one can add ufsd in the /etc/initramfs-tools/modules file and run sudo update-initramfs -u) this way ufsd module will always be loaded early in the boot step

I use that driver [with dracut](https://github.com/antonio-petricca/buddy-linux), which embeds it into the ramfs. For that reason I have never encountered the issue you described.

**Pull request merged**
